import { Store } from './store';
import { Company } from './company';
import { University } from './university';
import { Country } from './country';
import { Area } from './area';

export class Candidate {
  employee_id: number;
  candidate_id: number;
  candidate_uid: string;
  candidate_area_uuid: string;
  store_id: number;
  bank_id: number;
  university_id: number;
  country_id: number;
  bank_account_name: string;
  candidate_iban: string;
  candidate_name: string;
  candidate_name_ar: string;
  candidate_personal_photo: string;
  candidate_email: string;
  candidate_phone: string;
  candidate_address_line1;
  candidate_birth_date: string;
  candidate_civil_id: string;
  candidate_civil_expiry_date: string;
  candidate_civil_photo_front: string;
  candidate_civil_photo_back: string;
  candidate_hourly_rate: string;
  candidate_status: string;
  approved: number;
  isProfileCompleted: any;
  candidate_job_search_status: any;
  candidate_committed: any;
  age: string;
  candidate_objective: string;
  candidate_gender: any;
  candidate_driving_license: any;
  candidate_email_verification: any;
  skill: string;
  experience: string;
  candidate_resume: string;
  candidate_video: string;
  candidate_video_processed: any;
  candidate_created_at: string;
  candidate_updated_at: string;
  candidate_mom_kuwaiti: any;
  workHistory: any;
  rejectionRatio: any;
  acceptanceRatio: any;
  candidate_latitude: any;
  candidate_longitude: any;
  suggested: number;
  suggestionAccepted: number;
  suggestionRejected: number;
  currency_code: string;
  store: Store;
  company: Company;
  university: University;
  country: Country;
  area: Area;
  nationality: Country;
  candidateExperiences: any;
  candidateSkills: any;
  candidateIdCard: any;
  pendingField: any[];
  invitedCount: number;
  isInvitedForCompany: any;
}

export class CandidateWorkingHour {
  candidate_working_hour_uuid: string;
  candidate_id: number;
  store_id: number;
  date: string;
  start_time: string;
  end_time: string;
  total_time: number;
  start_location_lat: string;
  start_location_long: string;
  end_location_lat: string;
  end_location_long: string;
  created_at: string;
  updated_at: string;
  store: Store;
  candidate: Candidate;
}
