import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from "@angular/router";
import { AlertController, LoadingController, NavController, ToastController } from "@ionic/angular";
//models
import { Transfer } from "src/app/models/transfer";
import { Invoice } from "src/app/models/invoice";
//service
import { TransferService } from "src/app/providers/logged-in/transfer.service";
import { AwsService } from 'src/app/providers/aws.service';
import { TranslateLabelService } from "../../../../providers/translate-label.service";
import { AnalyticsService } from 'src/app/providers/analytics.service';


@Component({
  selector: 'app-transfer-view',
  templateUrl: './transfer-view.page.html',
  styleUrls: ['./transfer-view.page.scss'],
})
export class TransferViewPage implements OnInit {

  public transfer_id;
  public transfer: Transfer;
  public invoices: Invoice[] = []; // unpaid invoices
  public receipts: Invoice[] = []; // paid invoices
  public loading = false;

  public transferStatus = '';
  public transferStatusDescription = '';

  public borderLimit;

  constructor(
    public navCtrl: NavController,
    public aws: AwsService,
    public transferService: TransferService,
    private _loadingCtrl: LoadingController,
    public activatedRoute: ActivatedRoute,
    public alertCtrl: AlertController,
    public _toastCtrl: ToastController,
    public translateService: TranslateLabelService,
    public analyticService: AnalyticsService
  ) {
  }

  ngOnInit() {

    this.analyticService.page('Transfer View Page');

    this.transfer_id = this.activatedRoute.snapshot.paramMap.get('id');
    
    this.loadData();
  }

  ionViewWillLeave() {
    this.analyticService.track('page_exit', {
      'page': 'Transfer View Page'
    });  
  }

  ionViewWillEnter() {
    if (history.state && history.state.refresh) {
      this.loadData();
    }
  }

  async loadData() {
    // Load list of transfer
    this.loading = true;

    this.transferService.transferIdDetails(this.transfer_id).subscribe(response => {
      
      this.transfer = response;

      this._updateTransferStatus();

      this.receipts = [];
      this.invoices = [];

      response.invoices.forEach((value, index) => {
        if (value.invoice_status == 'paid') {
          this.receipts.push(value);
        } else {
          this.invoices.push(value);
        }
      });
      this.loading = false;
    });
  }

  /**
   * Update transfer status and description based on return value from API
   */
  private _updateTransferStatus() {
    switch (this.transfer.transfer_status) {
      case 0: // Cancelled
        this.transferStatus = 'Transfer Cancelled';
        this.transferStatusDescription = '\'Cancel Transfer\' for generated by mistake or having wrong input.';
        break;
      case 10: // Draft
        this.transferStatus = this._translate('Transfer Draft');
        this.transferStatusDescription = this._translate('`Lock Transfer` once you are done inputting hours worked by your assigned employees. Invoices will be sent to you after lock.');
        break;
      case 5: // Transfer Locked
        this.transferStatus = this._translate('Waiting for your payment');
        this.transferStatusDescription = this._translate('Invoices for this transfer has been sent to you and are available for download below.');
        break;
      case 1: // Payment Sent
        this.transferStatus = this._translate('Payment Sent');
        this.transferStatusDescription = this._translate('Waiting for bank to verify payment received to start distribution of payment.');
        break;
      case 3: // Distribution in Progress
        this.transferStatus = this._translate('Distribution in Progress');
        this.transferStatusDescription = this._translate('Your payment has been received and is currently being distributed to your assigned employees.');
        break;
      case 4: // Transfer Complete
        this.transferStatus = this._translate('Transfer Complete');
        this.transferStatusDescription = this._translate('All done!');
        break;
    }
  }

  async markCancel() {

    let alert = await this.alertCtrl.create({
      header:  this.translateService.transform('Cancel transfer?'),
      message: this.translateService.transform('Do you want to change status to Cancelled?'),
      buttons: [
        {
          text: this.translateService.transform('No'),
          role: 'cancel'
        },
        {
          text: this.translateService.transform('Yes'),
          handler: async () => {

            const loader = await this._loadingCtrl.create();
            loader.present(); 

            this.transferService.markCancel(this.transfer).subscribe(async response => {
              
              const toast = await this._toastCtrl.create({
                message: this.translateService.errorMessage(response.message),
                duration: 3000
              });
              toast.present();
 
              this.loadData();
              loader.dismiss();
            });
          }
        }
      ]
    });
    alert.present();
  }

  /**
   * Transfer Locking
   */
  async transferLock(transfer: Transfer) {
    // Load list of transfer
    const alert = await this.alertCtrl.create({
      header: this.translateService.transform('Confirm locking the transfer?'),
      message: this.translateService.transform("You will no longer be able to edit the transfer once it's locked."),
      buttons: [
        {
          text: this.translateService.transform('No'),
          role: 'cancel'
        },
        {
          text: this.translateService.transform('Yes'),
          handler: async () => {
            const loader = await this._loadingCtrl.create();
            loader.present();
            this.transferService.makeTransfertoLock(transfer).subscribe(async response => {

              const toast = await this._toastCtrl.create({
                message: this.translateService.errorMessage(response.message),
                duration: 3000
              });
              toast.present();

              this.loadData();
              loader.dismiss();
            });
          }
        }
      ]
    });
    alert.present();
  }

  /**
   * Marking Transfer as Payment Sent
   */
  async paymentSent(transfer: Transfer) {
    const loader = await this._loadingCtrl.create();
    loader.present();
    this.transferService.makePaymentSent(transfer).subscribe(async response => {

      const toast = await this._toastCtrl.create({
        message: this.translateService.errorMessage(response.message),
        duration: 3000
      });
      toast.present();

      this.loadData();
      loader.dismiss();
    });
  }

  /**
   * Download the receipt as specified by invoice_id
   * @param invoice
   */
  async downloadReceipt(invoice: Invoice) {
    const loader = await this._loadingCtrl.create();
    loader.present();
    this.transferService.downloadReceipt(invoice).subscribe(response => {
      // this.navCtrl.pop();
      loader.dismiss();
    });
  }

  /**
   * Download the invoice as specified by invoice_id
   * @param invoice
   */
  async downloadInvoice(invoice: Invoice) {
    const loader = await this._loadingCtrl.create();
    loader.present();
    this.transferService.downloadInvoice(invoice).subscribe(response => {
      loader.dismiss();
    });
  }

  /**
   * Load the Transfer form page to edit the transfer details
   */
  edit(transfer: any) {
    this.navCtrl.navigateForward('transfer-form/' + transfer.transfer_id, {
      state: {
        model: transfer
      }
    });
  }


  /**
   * Delete the transfer
   * @param transfer
   */
  async delete(transfer: Transfer) {
    const alert = await this.alertCtrl.create({
      header: this.translateService.transform('Do you really want to delete this transfer?'),
      buttons: [
        {
          text: this.translateService.transform('No'),
          role: 'cancel'
        },
        {
          text: this.translateService.transform('Yes'),
          handler: () => {
            this.deleteConfirmed(transfer);
          }
        }
      ]
    });
    alert.present();
  }

  /**
   * Confirm deletion of the transfer
   * @param transfer
   */
  async deleteConfirmed(transfer: Transfer) {
    const loader = await this._loadingCtrl.create();
    loader.present();
    this.transferService.delete(transfer).subscribe(async response => {
      loader.dismiss();

      if (response.operation == 'success') {
        this.navCtrl.pop();
      } else {
        const alert = await this.alertCtrl.create({
          message: this.translateService.errorMessage(response.message),
          buttons: ['Okay']
        });
        alert.present();
      }
    });
  }

  /**
   * On Candidate Selected
   * @param model
   */
  loadCandidateDetail(model) {
    this.navCtrl.navigateForward('candidate-view/' + model.candidate_id, {
      state: {
        model
      }
    });
  }

  /**
   * Calculating Total per Candidate
   */
  total(candidate) {
    return Number(
      (candidate.company_hourly_rate * candidate.hours) 
      + ((candidate.company_hourly_rate / 60) * candidate.minutes) 
      + ((candidate.company_hourly_rate/ 3600) * candidate.seconds) 
      + candidate.bonus 
      + candidate.transfer_cost
    ).toFixed(3);
  }

  logScrolling(e) {
    this.borderLimit = (e.detail.scrollTop > 20);
  }

  importTransfer(transfer: Transfer) {
    this.navCtrl.navigateForward('import-transfer-form/' + transfer.transfer_id, {
      state: {
        transfer
      }
    });
  }

  back() {
    return this.navCtrl.navigateBack('/view/transfer');
  }

  loadLogo($event, candidate) {
    candidate.candidate_personal_photo = null;
  }

  /**
   * Make date readable by Safari
   * @param date
   */
   toDate(date) {
    if (date) {
      return new Date(date.replace(/-/g, '/'));
    }
  }
  
  _translate(key) {
    return this.translateService.transform(key);
  }
}
